-- MySQL Script generated by MySQL Workbench
-- 08/15/15 02:03:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LMPE_Marrakech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LMPE_Marrakech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LMPE_Marrakech` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `LMPE_Marrakech` ;

-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`article` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `titre_article` VARCHAR(255) NULL,
  `id_media_article` INT NULL,
  `text_article` LONGTEXT NULL,
  `visible_article` TINYINT(1) NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`catigorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`catigorie` (
  `id_catigorie` INT NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(255) NULL,
  `discription_categorie` VARCHAR(255) NULL,
  PRIMARY KEY (`id_catigorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`utilisateur` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email_user` VARCHAR(255) NULL,
  `id_rang_user` INT NULL,
  `mot_de_passe_user` VARCHAR(255) NULL,
  `date_insc_user` DATE NULL,
  `nom_user` VARCHAR(255) NULL,
  `prenom_user` VARCHAR(255) NULL,
  `newslettre_user` TINYINT(1) NULL,
  `statut_social_user` VARCHAR(255) NULL,
  `genre_user` VARCHAR(255) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`rang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`rang` (
  `id_rang` INT NOT NULL AUTO_INCREMENT,
  `titre_rang` VARCHAR(255) NULL,
  `permition_rang` VARCHAR(255) NULL,
  PRIMARY KEY (`id_rang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`mediatheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`mediatheque` (
  `id_mediatheque` INT NOT NULL AUTO_INCREMENT,
  `titre_media` VARCHAR(255) NULL,
  `lien_media` VARCHAR(255) NULL,
  `id_format_media` INT NULL,
  `discription_media` VARCHAR(255) NULL,
  `visible_media` TINYINT(1) NULL,
  PRIMARY KEY (`id_mediatheque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`format` (
  `id_format` INT NOT NULL AUTO_INCREMENT,
  `type_format` VARCHAR(255) NULL,
  `ext_format` LONGTEXT NULL,
  PRIMARY KEY (`id_format`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`newslettre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`newslettre` (
  `id_newslettre` INT NOT NULL AUTO_INCREMENT,
  `objet_newslettre` VARCHAR(255) NULL,
  `text_newslettre` VARCHAR(255) NULL,
  `date-envoie_newslettre` DATE NULL,
  `id_media_newslettre` VARCHAR(255) NULL,
  PRIMARY KEY (`id_newslettre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`inscrit_newslettre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`inscrit_newslettre` (
  `id_inscrit_newslettre` INT NOT NULL AUTO_INCREMENT,
  `email_inscrit` VARCHAR(255) NULL,
  PRIMARY KEY (`id_inscrit_newslettre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`press`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`press` (
  `id_press` INT NOT NULL AUTO_INCREMENT,
  `tittre_press` VARCHAR(255) NULL,
  `lien_press` VARCHAR(255) NULL,
  `id_support_press` INT NULL,
  `date_press` DATE NULL,
  PRIMARY KEY (`id_press`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`support` (
  `id_support` INT NOT NULL AUTO_INCREMENT,
  `nom_support` VARCHAR(255) NULL,
  `id_type_support` INT NULL,
  `icon_support` VARCHAR(255) NULL,
  PRIMARY KEY (`id_support`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LMPE_Marrakech`.`type_support_press`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LMPE_Marrakech`.`type_support_press` (
  `id_type_support_press` INT NOT NULL AUTO_INCREMENT,
  `nom_type_support_press` VARCHAR(255) NULL,
  `desc_type_support_press` VARCHAR(255) NULL,
  PRIMARY KEY (`id_type_support_press`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
